[tool.poetry]
name = "controller-new"
version = "0.1.0"
description = ""
authors = ["Mark <74201924+Markushik@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "controller_new"}]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.0.0b7"
sqlalchemy = "^2.0.4"
asyncpg = "^0.27.0"
dynaconf = "^3.1.12"
redis = "^4.5.5"
aiogram-dialog = "^2.0.0b18"
taskiq = "^0.6.0"
taskiq-redis = "^0.3.1"
taskiq-nats = "^0.2.0"
loguru = "^0.7.0"
alembic = "^1.11.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.247"

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
