[tool.poetry]
name = "controller-new"
version = "0.1.0"
description = ""
authors = ["Mark <74201924+Markushik@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "controller_new"}]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.0.0b7"
sqlalchemy = "^2.0.4"
asyncpg = "^0.27.0"
dynaconf = "^3.1.12"
redis = "^4.5.5"
aiogram-dialog = "^2.0.0b20"
loguru = "^0.7.0"
fluentogram = "^1.1.6"
alembic = "^1.11.1"
asyncstdlib = "^3.10.8"
nats-py = "^2.3.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.272"

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
