[default]
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DATABASE = 7

POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432
POSTGRES_USERNAME = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_DATABASE = "postgres"

[production]

[development]
