[development]

    [development.redis]
        REDIS_HOST = '127.0.0.1'  # redis
        REDIS_PORT = 6379
        REDIS_DATABASE = 7

    [development.postgres]
        POSTGRES_HOST = '127.0.0.1'  # postgres
        POSTGRES_PORT = 5432
        POSTGRES_USERNAME = 'postgres'
        POSTGRES_PASSWORD = 'postgres'
        POSTGRES_DATABASE = 'postgres'

    [development.nats]
        NATS_HOST = '127.0.0.1'  # nats
        NATS_PORT = 4222
