name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade Pip
        run: |
          pip3 install --no-cache-dir --upgrade pip
      - name: Install Poetry
        run: |
          pip3 install --no-cache-dir setuptools wheel
          pip3 install --no-cache-dir poetry
      - name: Install Dependencies
        run: |
           poetry add ruff@latest --group dev
      - name: Run Ruff
        run: |
          poetry run ruff .
